[colors.primary]
background = '#0e1416'
foreground = '#dee3e5'

[colors.selection]
text = '#dee3e5'
background = '#004d5c'

[colors.cursor]
text = '#0e1416'
cursor = '#00bcd4'

[colors.normal]
black   = '#0e1416'
red     = '#fd1c5b'
green   = '#00d413'
yellow  = '#ffed00'
blue    = '#00b2c9'
magenta = '#005762'
cyan    = '#00bcd4'
white   = '#c3dbde'

[colors.bright]
black   = '#758789'
red     = '#ff3f82'
green   = '#4cfe5c'
yellow  = '#fff24c'
blue    = '#22d2e9'
magenta = '#4ceaff'
cyan    = '#8cf2ff'
white   = '#f2fdff'
